[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
mpl_core_examples = "6Ed2X36Cs6KkAGKKJgf2ZHusnuiGhsWDitaxgpTSbec9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
program = "tests/mpl_core_program.so"

[[test.genesis]]
address = "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"
program = "tests/spl_noop_program.so"

[test.validator]
bind_address = "0.0.0.0"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "AwPRxL5f6GDVajyE1bBcfSWdQT58nWMoS36A1uFtpCZY"
filename = "tests/oracle-account.json"
